name: kibana
version: 0.1.12
description: Sample chart template for registry
keywords:
- kubernetes
- logging
- data
- elasticsearch
- kibana
home: https://github.com/samsung-cnct/chart-kibana
sources:
- https://github.com/samsung-cnct/chart-kibana
maintainers:
- name: Samsung CNCT OSS Maintainers
  email: oss-maintainer@samsung-cnct.io
icon: https://github.com/samsung-cnct/solas/docs/images/samsung-logo.svg
engine: gotpl
# should match values.image version
appVersion: 6.4.2
