# Default values for kibana.
# Service
name: kibana-logging
app: kibana-logging
port: 5601

# Deployment
component: kibana-logging
replicas: 1
container_name: kibana-logging
image: docker.elastic.co/kibana/kibana:6.3.2
# keep request = limit to keep this container in guaranteed class
cpu_limit: 200m
cpu_requests: 200m
mem_limit: 4Gi
mem_requests: 4Gi
container_port: 5601

env:
  # All Kibana configuration options are adjustable via env vars.
  # To adjust a config option to an env var uppercase + replace `.` with `_`
  # Ref: https://www.elastic.co/guide/en/kibana/current/settings.html
  ELASTICSEARCH_URL: https://elasticsearch:9200
  # allow self-signed cert to be used by ElasticSearch
  ELASTICSEARCH_SSL_VERIFICATIONMODE: none
  XPACK_SECURITY_ENABLED: "true"
  # LOGGING_VERBOSE: "true"
  #
  #NOTE: THE PASSWORD SHOULD BE PASSED IN ON THE COMMAND LINE
security:
  # ELASTICSEARCH_USERNAME: 
  username: elastic
  # ELASTICSEARCH_PASSWORD:
  password: changeme
  
tolerations:
 # - key: taintKey
 #   value: taintValue
 #   operator: Equal
 #   effect: NoSchedule

#
#  Service options
#
#  default type is LoadBalancer
#  With annotation: loadBalancer + external-dns 
#  
#  NOTE: comment out the annotations, or specifically 
#  the external-dns.alpha.kubernetes.io/hostname annotation and value, 
#  if you are using an Ingress setup instead
#
#  recommended type is ClusterIP + Ingress
#  (type: ClusterIP     ingress.enabled: true)
service:
  type: LoadBalancer
  annotations:
    # Replace <mydomain>.cluster.cncnt.io with your real domain in route53
    # NOTE: the default is an invalid domain and will not be created if not set correctly.
  - key: external-dns.alpha.kubernetes.io/hostname
    value: "kibana.<mydomain>.cluster.cnct.io"

#  disabled by default as not all kubernetes clusters will have a default
#  ingress controller available
ingress:
  enabled: false
  annotations:
  - key: kubernetes.io/tls-acme
    value: "true"
  - key: kubernetes.io/ingress.class
    value: "nginx"
  - key: nginx.ingress.kubernetes.io/auth-type
    value: basic
  - key: nginx.ingress.kubernetes.io/auth-secret
    value: basic-auth
  - key: nginx.ingress.kubernetes.io/auth-realm
    value: "Authentication required for kibana"
  tls:
    enabled: false  #  enabling this assumes you have kube-lego running and assumes ingress.host is the same for tls  
  host: kibana.externally-visible-dns.org
  auth: "uid:<MD5 has of password>\n"  #  username and password for accessing kibana.  set to empty for no auth, recommend using `htpasswd` locally and copying resultant MD5

scheduling:
  affinity:
    node:
      type: #requiredDuringSchedulingIgnoredDuringExecution
      labels:
      # - key: iamalabelkey
      #   operator: In
      #   values: ["value1", "value2"]
