{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.name}}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range .Values.ingress.annotations }}
    {{ .key }}: "{{ .value }}"
    {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-central
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "namewithversion" . }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts: 
    - {{ .Values.ingress.host }}
    secretName: {{.Values.name}}-tls
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{.Values.name}}
          servicePort: {{.Values.port}}

{{- end }}